---
- name: Install reqiuered packages for ownCloud
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - mariadb-server
      - openssl
      - php-imagick
      - php-common
      - php-curl
      - php-gd
      - php-imap
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-ssh2
      - php-xml
      - php-zip
      - php-apcu
      - php-redis
      - redis-server
      - wget